export enum GenreEnum {
  SCIENCE_FICTION = 'SCIENCE_FICTION',
  FANTASY = 'FANTASY',
  MYSTERY = 'MYSTERY',
  ROMANCE = 'ROMANCE',
  HISTORY = 'HISTORY',
  BIOGRAPHY = 'BIOGRAPHY',
  ADVENTURE = 'ADVENTURE',
}
